version: '3.9'

services:
  engineering_thesis_db:
    image: postgres:15.1
    container_name: engineering_thesis_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=engineering_thesis_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
  engineering_thesis_web:
    image: engineering_thesis_web
    container_name: engineering_thesis_web
    environment:
      - SECRET_KEY=secret_key
    volumes:
      - ./app:/app
    ports:
      - '8000:8000'
    command: bash -c 'uvicorn main:app --reload --host 0.0.0.0 --port 8000'
    depends_on:
      engineering_thesis_db:
        condition: service_healthy
