import string

SAFE_METHODS = ["GET", "HEAD", "OPTIONS", "TRACE"]

DOUBLE_SUBMIT_COOKIE_CSRF_PROTECTION_METHOD = "DOUBLE_SUBMIT_COOKIE"
SYNCHRONIZER_TOKEN_PATTERN_CSRF_PROTECTION_METHOD = "SYNCHRONIZER_TOKEN_PATTERN"

CSRF_TOKEN_NAME = "csrf_token"
CSRF_TOKEN_LENGTH = 32
CSRF_TOKEN_ALLOWED_CHARS = string.ascii_letters + string.digits
